name             'passenger_nginx'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures passenger_nginx'
long_description 'Installs/Configures passenger_nginx'
version          '0.5.1'
depends          'apt-repo'
depends          'fail2ban'
